export const skills = [
  { label: "Backend & Runtime", color: "from-violet-500 to-purple-400", tags: ["Node.js", "Python", "FastAPI", "Express", "node-cron", "REST APIs"] },
  { label: "Frontend",     color: "from-blue-500 to-cyan-400",    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS", "HTML5/CSS3"] },
  { label: "AI & LLM",     color: "from-indigo-500 to-cyan-400", tags: ["OpenAI API", "Anthropic API (Claude)", "Gemini API", "LangChain", "OpenRouter", "Agents SDK", "MCP"] },
  { label: "Integrations", color: "from-green-500 to-emerald-400", tags: ["Slack Bot & Events API", "Google Sheets", "Google Calendar", "Gmail API", "Webhooks", "WhatsApp", "Twilio"] },
  { label: "Cloud & DevOps", color: "from-sky-500 to-blue-400",   tags: ["Railway", "Docker", "Kubernetes", "Kafka", "Dapr", "CI/CD", "GitHub"] },
  { label: "Database",     color: "from-rose-500 to-pink-400",    tags: ["MongoDB", "PostgreSQL", "Sanity CMS"] },
  { label: "Architecture", color: "from-teal-500 to-cyan-400",    tags: ["Event-Driven", "Spec-Driven", "Fuzzy Matching / Alias Resolution", "BG Precompute & Caching", "Rate-Limit-Safe Pipelines"] },
];

export const projects = [
  {
    title: "Slack/Google Automation Suite",
    subtitle: "Production · Heat Wave Pest Control",
    desc: "Five interconnected production automation systems for a U.S. multi-region pest-control operation: a Specialty Form Compliance Bot (token-based property matching with Levenshtein fuzzy matching + alias layer across 123 properties), a real-time Notes Verification Bot with 15-min escalation, an automated Weekly Reporting Suite, and a Specialty Recommendation engine with tier-aware pricing.",
    tags: ["Node.js", "Slack API", "Google Sheets", "OpenRouter", "Railway"],
    icon: "🛰️", accent: "from-indigo-500 to-violet-500", live: null,
  },
  {
    title: "Live Operations Dashboard",
    subtitle: "Production · Web App",
    desc: "Password-protected ops dashboard (Express + vanilla JS) with six live sections — Overview, Route Timing, Units Allocation, Notes Bot Activity, Recommendations Tracking & Monthly Per-Technician Reporting. Slack-history route-timing engine, background precompute + snapshot caching (cut load from 60–90s timeouts to instant), and one-click CSV export.",
    tags: ["Express", "JavaScript", "Slack API", "BG Precompute", "Caching"],
    icon: "📊", accent: "from-sky-500 to-blue-500", live: null,
  },
  {
    title: "Autonomous AI Marketing Agency",
    subtitle: "Hackathon 2024 · Hugging Face",
    desc: "Fully autonomous AI marketing agency that handles campaign strategy, content generation, and client outreach — built as a live startup and deployed on Hugging Face Spaces.",
    tags: ["Python", "AI Agents", "FastAPI", "OpenAI API", "Automation"],
    icon: "📣", accent: "from-indigo-500 to-cyan-500",
    live: "https://naveedtechlab-autonomous-ai-marketing-agency.hf.space/",
  },
  {
    title: "Personal AI Employee",
    subtitle: "Hackathon 2024 · Digital FTE",
    desc: "Autonomous AI employee with Gmail/WhatsApp automation, Obsidian memory system, and MCP tools — running 24/7 without human intervention.",
    tags: ["OpenAI SDK", "MCP", "Gmail API", "WhatsApp", "Python"],
    icon: "🤖", accent: "from-indigo-500 to-violet-500", live: null,
  },
  {
    title: "CRM Digital FTE",
    subtitle: "CRM Agent · Hugging Face",
    desc: "Multi-channel customer support agent handling Gmail, WhatsApp, and Web forms with a PostgreSQL ticket system and FastAPI backend.",
    tags: ["FastAPI", "PostgreSQL", "LangChain", "Twilio", "Python"],
    icon: "🎯", accent: "from-blue-500 to-cyan-500",
    live: "https://naveedtechlab-crm-digital-fte.hf.space",
  },
  {
    title: "Course Companion FTE",
    subtitle: "AI Tutor · Hugging Face",
    desc: "AI-powered tutoring assistant with deterministic backend logic, skills-based agent architecture, and an interactive learning interface.",
    tags: ["Python", "OpenAI API", "FastAPI", "Streamlit"],
    icon: "📚", accent: "from-violet-500 to-purple-500",
    live: "https://naveedtechlab-course-companion-fte.hf.space",
  },
  {
    title: "Todo App Phase 5",
    subtitle: "Full Stack · Hugging Face",
    desc: "Spec-driven todo app evolved from console to full-stack with AI chatbot, cloud-native deployment, and OpenAI Agents SDK integration.",
    tags: ["Next.js", "FastAPI", "OpenAI SDK", "Docker"],
    icon: "✅", accent: "from-green-500 to-emerald-500",
    live: "https://naveedtechlab-todo-app-phase5.hf.space",
  },
  {
    title: "LearnFlow",
    subtitle: "Learning Platform · Hugging Face",
    desc: "Interactive AI-assisted learning flow platform with structured modules and an intuitive UI for seamless education experiences.",
    tags: ["Python", "AI", "Streamlit", "OpenAI API"],
    icon: "🎓", accent: "from-sky-500 to-blue-500",
    live: "https://naveedtechlab-learnflow.hf.space",
  },
  {
    title: "AI Native Textbook",
    subtitle: "EdTech · Vercel",
    desc: "AI-native digital textbook delivering interactive, intelligent content — blending traditional learning with generative AI capabilities.",
    tags: ["Next.js", "OpenAI API", "Vercel", "TypeScript"],
    icon: "📖", accent: "from-indigo-500 to-violet-500",
    live: "https://ai-native-textbook1.vercel.app/",
  },
  {
    title: "E-Commerce Store",
    subtitle: "Freelance · Vercel",
    desc: "Modern full-featured e-commerce web app with product listings, cart functionality, and a clean responsive UI — deployed on Vercel.",
    tags: ["Next.js", "React", "Tailwind CSS", "Vercel"],
    icon: "🛍️", accent: "from-rose-500 to-pink-500",
    live: "https://e-comm-naveed.vercel.app/",
  },
  {
    title: "Library Manager",
    subtitle: "Utility App · Streamlit",
    desc: "Smart library management system to add, search, and manage books with an intuitive Streamlit interface and persistent data storage.",
    tags: ["Python", "Streamlit", "Pandas"],
    icon: "📕", accent: "from-emerald-500 to-teal-500",
    live: "https://naveed247365-library-manager-library-manager-iykdx8.streamlit.app/",
  },
  {
    title: "Number Guessing Game",
    subtitle: "Fun App · Streamlit",
    desc: "Interactive browser-based number guessing game with difficulty levels and score tracking built with Python and Streamlit.",
    tags: ["Python", "Streamlit", "Game Logic"],
    icon: "🎮", accent: "from-teal-500 to-cyan-500",
    live: "https://naveed247365-number-guessing-game-guessing-game-kfloll.streamlit.app/",
  },
  {
    title: "Password Strength Meter",
    subtitle: "Security Tool · Streamlit",
    desc: "Real-time password strength analyzer with visual feedback, entropy scoring, and security suggestions.",
    tags: ["Python", "Streamlit", "Security", "GUI"],
    icon: "🔐", accent: "from-red-500 to-rose-500",
    live: "https://password-strength-meter-with-a-gui.streamlit.app/",
  },
  {
    title: "Secure Data Vault",
    subtitle: "Encryption App · Streamlit",
    desc: "End-to-end data encryption system to securely store and retrieve sensitive information using modern cryptographic algorithms.",
    tags: ["Python", "Cryptography", "Streamlit", "Security"],
    icon: "🔒", accent: "from-slate-500 to-gray-600",
    live: "https://naveed247365-secure-data-encryption-system--secure-vault-sbgxir.streamlit.app/",
  },
  {
    title: "Unit Converter",
    subtitle: "Utility Tool · Streamlit",
    desc: "Comprehensive unit conversion tool supporting length, weight, temperature, speed, and more — with a fast Streamlit interface.",
    tags: ["Python", "Streamlit", "Math"],
    icon: "📐", accent: "from-indigo-500 to-violet-500",
    live: "https://naveed247365-unit-converter-unit-converter-cycms9.streamlit.app/",
  },
  {
    title: "Streamlit Web App",
    subtitle: "Web App · Streamlit",
    desc: "Dynamic multi-feature web application showcasing Python-powered interactivity, data visualization, and UI components.",
    tags: ["Python", "Streamlit", "Data Viz"],
    icon: "🌐", accent: "from-fuchsia-500 to-pink-500",
    live: "https://naveed247365-web-app-with-streamlit-app-hnkir1.streamlit.app/",
  },
  {
    title: "Fiverr Freelance Work",
    subtitle: "Freelance · Client Projects",
    desc: "Shopify stores, custom dashboards, CMS-based websites, and automation workflows for clients — from design to deployment.",
    tags: ["Shopify", "React", "Sanity CMS", "Node.js"],
    icon: "💼", accent: "from-yellow-500 to-green-400", live: null,
  },
];

export const experience = [
  {
    icon: "🛰️", title: "AI Automation Engineer (Forward-Deployed)",
    org: "Activus Capital Partners — Heat Wave Pest Control", period: "Apr 2026 – Present",
    accent: "from-indigo-500 to-violet-500",
    desc: "Own and operate five production Slack/Google Workspace automation systems plus a live operations dashboard for a U.S. multi-region pest-control company — supporting 8+ field technicians across 123 properties. Compliance bots, notes verification, weekly reporting, a recommendation engine, and a route-timing dashboard, with daily production monitoring, root-cause debugging, and same-day fixes. Report directly to the Managing Partner, Operations Coordinator & Director.",
    live: null,
  },
  {
    icon: "🏢", title: "Founder & Lead Developer",
    org: "NaveedTechLab · Digital Agency", period: "2025 – Present",
    accent: "from-violet-500 to-purple-500",
    desc: "Built a digital agency targeting local Karachi businesses — secured first two clients (CCTV World Karachi & Ha-Aeen Dentistry). Produced 6-month digital transformation roadmaps, partner agreements, and pricing strategy; delivered digital footprint setup, customer-acquisition systems, and workflow automation.",
    live: null,
  },
  {
    icon: "💻", title: "Freelance Full Stack Developer",
    org: "Fiverr & Direct Clients · Remote", period: "2023 – Present",
    accent: "from-blue-500 to-cyan-500",
    desc: "Delivered Shopify stores, business websites, custom dashboards, CMS-based sites, and automation workflows end-to-end — from requirements through design, development, and deployment.",
    live: null,
  },
  {
    icon: "📱", title: "Mobile Software Technician",
    org: "Sareena Mobile Market", period: "Past Experience",
    accent: "from-blue-500 to-cyan-500",
    desc: "Performed mobile software flashing, firmware updates, and software recovery for a wide range of Android and feature phones in a high-volume repair environment.",
    live: null,
  },
  {
    icon: "🥽", title: "VR Experience Designer",
    org: "Freelance / Event-Based", period: "Past Experience",
    accent: "from-violet-500 to-purple-500",
    desc: "Designed and set up immersive VR sitting and riding simulation experiences for events, including hardware configuration and user experience flow.",
    live: null,
  },
  {
    icon: "🎮", title: "Kinect Gaming Manager",
    org: "Mufti Ramzan Park · Xbox 360 Kinect", period: "6 Months",
    accent: "from-green-500 to-emerald-500",
    desc: "Designed and managed a large-scale Kinect-based interactive gaming setup on a 12-foot screen at Mufti Ramzan Park. Handled installation, daily operations, and visitor engagement.",
    live: null,
  },
  {
    icon: "🏢", title: "Operations Manager",
    org: "Marble Shop", period: "1 Year",
    accent: "from-sky-500 to-blue-500",
    desc: "Managed day-to-day operations of a marble retail business — overseeing inventory, vendor relations, staff coordination, and customer sales.",
    live: null,
  },
  {
    icon: "🔧", title: "Owner – Marble Machine Parts Workshop",
    org: "Self-Employed Business", period: "5 Years",
    accent: "from-rose-500 to-pink-500",
    desc: "Ran an independent workshop manufacturing and supplying spare parts for marble cutting and polishing machinery. Managed production, client orders, and business operations end-to-end.",
    live: null,
  },
];

